// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type CacheVerificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewQuery       string                 `protobuf:"bytes,1,opt,name=new_query,json=newQuery,proto3" json:"new_query,omitempty"`
	CachedQuery    string                 `protobuf:"bytes,2,opt,name=cached_query,json=cachedQuery,proto3" json:"cached_query,omitempty"`
	CachedResponse string                 `protobuf:"bytes,3,opt,name=cached_response,json=cachedResponse,proto3" json:"cached_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CacheVerificationRequest) Reset() {
	*x = CacheVerificationRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerificationRequest) ProtoMessage() {}

func (x *CacheVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerificationRequest.ProtoReflect.Descriptor instead.
func (*CacheVerificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *CacheVerificationRequest) GetNewQuery() string {
	if x != nil {
		return x.NewQuery
	}
	return ""
}

func (x *CacheVerificationRequest) GetCachedQuery() string {
	if x != nil {
		return x.CachedQuery
	}
	return ""
}

func (x *CacheVerificationRequest) GetCachedResponse() string {
	if x != nil {
		return x.CachedResponse
	}
	return ""
}

type CacheVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probability   float32                `protobuf:"fixed32,1,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheVerificationResponse) Reset() {
	*x = CacheVerificationResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerificationResponse) ProtoMessage() {}

func (x *CacheVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerificationResponse.ProtoReflect.Descriptor instead.
func (*CacheVerificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *CacheVerificationResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Cached        bool                   `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x0esemantic_cache\":\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"+\n" +
	"\x11EmbeddingResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\"\x83\x01\n" +
	"\x18CacheVerificationRequest\x12\x1b\n" +
	"\tnew_query\x18\x01 \x01(\tR\bnewQuery\x12!\n" +
	"\fcached_query\x18\x02 \x01(\tR\vcachedQuery\x12'\n" +
	"\x0fcached_response\x18\x03 \x01(\tR\x0ecachedResponse\"=\n" +
	"\x19CacheVerificationResponse\x12 \n" +
	"\vprobability\x18\x01 \x01(\x02R\vprobability\"?\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached2\xcd\x01\n" +
	"\x0eEncoderService\x12N\n" +
	"\fGetEmbedding\x12\x1b.semantic_cache.TextRequest\x1a!.semantic_cache.EmbeddingResponse\x12k\n" +
	"\x14VerifyCachedResponse\x12(.semantic_cache.CacheVerificationRequest\x1a).semantic_cache.CacheVerificationResponse2\\\n" +
	"\x0eCoreAppService\x12J\n" +
	"\fProcessQuery\x12\x1b.semantic_cache.TextRequest\x1a\x1d.semantic_cache.QueryResponseB.Z,github.com/THETITAN220/FSCgRPC/gateway/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_goTypes = []any{
	(*TextRequest)(nil),               // 0: semantic_cache.TextRequest
	(*EmbeddingResponse)(nil),         // 1: semantic_cache.EmbeddingResponse
	(*CacheVerificationRequest)(nil),  // 2: semantic_cache.CacheVerificationRequest
	(*CacheVerificationResponse)(nil), // 3: semantic_cache.CacheVerificationResponse
	(*QueryResponse)(nil),             // 4: semantic_cache.QueryResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: semantic_cache.EncoderService.GetEmbedding:input_type -> semantic_cache.TextRequest
	2, // 1: semantic_cache.EncoderService.VerifyCachedResponse:input_type -> semantic_cache.CacheVerificationRequest
	0, // 2: semantic_cache.CoreAppService.ProcessQuery:input_type -> semantic_cache.TextRequest
	1, // 3: semantic_cache.EncoderService.GetEmbedding:output_type -> semantic_cache.EmbeddingResponse
	3, // 4: semantic_cache.EncoderService.VerifyCachedResponse:output_type -> semantic_cache.CacheVerificationResponse
	4, // 5: semantic_cache.CoreAppService.ProcessQuery:output_type -> semantic_cache.QueryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
