// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncoderService_GetEmbedding_FullMethodName         = "/semantic_cache.EncoderService/GetEmbedding"
	EncoderService_VerifyCachedResponse_FullMethodName = "/semantic_cache.EncoderService/VerifyCachedResponse"
)

// EncoderServiceClient is the client API for EncoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncoderServiceClient interface {
	GetEmbedding(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	VerifyCachedResponse(ctx context.Context, in *CacheVerificationRequest, opts ...grpc.CallOption) (*CacheVerificationResponse, error)
}

type encoderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncoderServiceClient(cc grpc.ClientConnInterface) EncoderServiceClient {
	return &encoderServiceClient{cc}
}

func (c *encoderServiceClient) GetEmbedding(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, EncoderService_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encoderServiceClient) VerifyCachedResponse(ctx context.Context, in *CacheVerificationRequest, opts ...grpc.CallOption) (*CacheVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheVerificationResponse)
	err := c.cc.Invoke(ctx, EncoderService_VerifyCachedResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncoderServiceServer is the server API for EncoderService service.
// All implementations must embed UnimplementedEncoderServiceServer
// for forward compatibility.
type EncoderServiceServer interface {
	GetEmbedding(context.Context, *TextRequest) (*EmbeddingResponse, error)
	VerifyCachedResponse(context.Context, *CacheVerificationRequest) (*CacheVerificationResponse, error)
	mustEmbedUnimplementedEncoderServiceServer()
}

// UnimplementedEncoderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncoderServiceServer struct{}

func (UnimplementedEncoderServiceServer) GetEmbedding(context.Context, *TextRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedEncoderServiceServer) VerifyCachedResponse(context.Context, *CacheVerificationRequest) (*CacheVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCachedResponse not implemented")
}
func (UnimplementedEncoderServiceServer) mustEmbedUnimplementedEncoderServiceServer() {}
func (UnimplementedEncoderServiceServer) testEmbeddedByValue()                        {}

// UnsafeEncoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncoderServiceServer will
// result in compilation errors.
type UnsafeEncoderServiceServer interface {
	mustEmbedUnimplementedEncoderServiceServer()
}

func RegisterEncoderServiceServer(s grpc.ServiceRegistrar, srv EncoderServiceServer) {
	// If the following call pancis, it indicates UnimplementedEncoderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncoderService_ServiceDesc, srv)
}

func _EncoderService_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncoderServiceServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncoderService_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncoderServiceServer).GetEmbedding(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncoderService_VerifyCachedResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncoderServiceServer).VerifyCachedResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncoderService_VerifyCachedResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncoderServiceServer).VerifyCachedResponse(ctx, req.(*CacheVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncoderService_ServiceDesc is the grpc.ServiceDesc for EncoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semantic_cache.EncoderService",
	HandlerType: (*EncoderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmbedding",
			Handler:    _EncoderService_GetEmbedding_Handler,
		},
		{
			MethodName: "VerifyCachedResponse",
			Handler:    _EncoderService_VerifyCachedResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

const (
	CoreAppService_ProcessQuery_FullMethodName = "/semantic_cache.CoreAppService/ProcessQuery"
)

// CoreAppServiceClient is the client API for CoreAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreAppServiceClient interface {
	ProcessQuery(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type coreAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreAppServiceClient(cc grpc.ClientConnInterface) CoreAppServiceClient {
	return &coreAppServiceClient{cc}
}

func (c *coreAppServiceClient) ProcessQuery(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, CoreAppService_ProcessQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreAppServiceServer is the server API for CoreAppService service.
// All implementations must embed UnimplementedCoreAppServiceServer
// for forward compatibility.
type CoreAppServiceServer interface {
	ProcessQuery(context.Context, *TextRequest) (*QueryResponse, error)
	mustEmbedUnimplementedCoreAppServiceServer()
}

// UnimplementedCoreAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreAppServiceServer struct{}

func (UnimplementedCoreAppServiceServer) ProcessQuery(context.Context, *TextRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessQuery not implemented")
}
func (UnimplementedCoreAppServiceServer) mustEmbedUnimplementedCoreAppServiceServer() {}
func (UnimplementedCoreAppServiceServer) testEmbeddedByValue()                        {}

// UnsafeCoreAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreAppServiceServer will
// result in compilation errors.
type UnsafeCoreAppServiceServer interface {
	mustEmbedUnimplementedCoreAppServiceServer()
}

func RegisterCoreAppServiceServer(s grpc.ServiceRegistrar, srv CoreAppServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreAppService_ServiceDesc, srv)
}

func _CoreAppService_ProcessQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreAppServiceServer).ProcessQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreAppService_ProcessQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreAppServiceServer).ProcessQuery(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreAppService_ServiceDesc is the grpc.ServiceDesc for CoreAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semantic_cache.CoreAppService",
	HandlerType: (*CoreAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessQuery",
			Handler:    _CoreAppService_ProcessQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
