services:
  redis-vector:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS="--appendonly yes"

  kafka-bus:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      [
        "redpanda",
        "start",
        "--mode",
        "dev-container",
        "--kafka-addr=PLAINTEXT://0.0.0.0:9092",
        "--advertise-kafka-addr=PLAINTEXT://127.0.0.1:9092",
        "--smp=1",
        "--memory=1G",
        "--set",
        "redpanda.auto_create_topics_enabled=true",
      ]
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/redpanda/data
volumes:
  redis_data:
  kafka_data:
