# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbedding = channel.unary_unary(
                '/semantic_cache.EncoderService/GetEmbedding',
                request_serializer=api__pb2.TextRequest.SerializeToString,
                response_deserializer=api__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.VerifyCachedResponse = channel.unary_unary(
                '/semantic_cache.EncoderService/VerifyCachedResponse',
                request_serializer=api__pb2.CacheVerificationRequest.SerializeToString,
                response_deserializer=api__pb2.CacheVerificationResponse.FromString,
                _registered_method=True)


class EncoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCachedResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=api__pb2.TextRequest.FromString,
                    response_serializer=api__pb2.EmbeddingResponse.SerializeToString,
            ),
            'VerifyCachedResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCachedResponse,
                    request_deserializer=api__pb2.CacheVerificationRequest.FromString,
                    response_serializer=api__pb2.CacheVerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic_cache.EncoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semantic_cache.EncoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_cache.EncoderService/GetEmbedding',
            api__pb2.TextRequest.SerializeToString,
            api__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCachedResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_cache.EncoderService/VerifyCachedResponse',
            api__pb2.CacheVerificationRequest.SerializeToString,
            api__pb2.CacheVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessQuery = channel.unary_unary(
                '/semantic_cache.CoreAppService/ProcessQuery',
                request_serializer=api__pb2.TextRequest.SerializeToString,
                response_deserializer=api__pb2.QueryResponse.FromString,
                _registered_method=True)


class CoreAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=api__pb2.TextRequest.FromString,
                    response_serializer=api__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic_cache.CoreAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semantic_cache.CoreAppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_cache.CoreAppService/ProcessQuery',
            api__pb2.TextRequest.SerializeToString,
            api__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
